In [ ]:
!pip install pandas
import pandas as pd
df=pd.read_csv("/content/Weather Test Data.csv")




In [ ]:
!pip install pandas#pandas---to read the dataset,,to manupulate the dataset


In [ ]:
!pip install numpy


In [ ]:
!pip install matplotlib
!pip install seaborn

In [ ]:
!pip install scikit-learn

In [ ]:
import pandas as pd
df=pd.read_csv("/content/Weather Test Data.csv")

In [ ]:
df

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,Row0,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
1,Row1,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
2,Row2,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,24.0,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No
3,Row3,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,28.0,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No
4,Row4,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,28.0,76.0,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42672,Row43633,Uluru,2.4,19.1,0.0,NaN,NaN,E,33.0,SE,...,17.0,59.0,24.0,1030.0,1026.2,NaN,NaN,8.0,18.8,No
42673,Row43634,Uluru,2.3,21.4,0.0,NaN,NaN,SE,22.0,SE,...,7.0,60.0,28.0,1026.9,1022.8,NaN,NaN,8.9,20.3,No
42674,Row43635,Uluru,2.6,22.5,0.0,NaN,NaN,S,19.0,S,...,7.0,59.0,24.0,1025.0,1021.4,NaN,NaN,8.8,22.1,No
42675,Row43636,Uluru,7.4,20.6,0.0,NaN,NaN,E,35.0,ESE,...,17.0,63.0,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,No


In [ ]:
df

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,Row0,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
1,Row1,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
2,Row2,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,24.0,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No
3,Row3,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,28.0,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No
4,Row4,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,28.0,76.0,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42672,Row43633,Uluru,2.4,19.1,0.0,NaN,NaN,E,33.0,SE,...,17.0,59.0,24.0,1030.0,1026.2,NaN,NaN,8.0,18.8,No
42673,Row43634,Uluru,2.3,21.4,0.0,NaN,NaN,SE,22.0,SE,...,7.0,60.0,28.0,1026.9,1022.8,NaN,NaN,8.9,20.3,No
42674,Row43635,Uluru,2.6,22.5,0.0,NaN,NaN,S,19.0,S,...,7.0,59.0,24.0,1025.0,1021.4,NaN,NaN,8.8,22.1,No
42675,Row43636,Uluru,7.4,20.6,0.0,NaN,NaN,E,35.0,ESE,...,17.0,63.0,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,No


In [ ]:
df.head(20)

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,Row0,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
1,Row1,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
2,Row2,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,24.0,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No
3,Row3,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,28.0,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No
4,Row4,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,28.0,76.0,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes
5,Row6,Albury,11.5,29.3,0.0,NaN,NaN,S,24.0,SE,...,9.0,56.0,28.0,1019.3,1014.8,NaN,NaN,19.1,27.3,No
6,Row7,Albury,16.2,33.9,0.0,NaN,NaN,WSW,35.0,SE,...,13.0,45.0,19.0,1010.9,1007.6,NaN,1.0,23.2,33.0,No
7,Row8,Albury,12.0,24.4,0.8,NaN,NaN,W,39.0,WNW,...,17.0,48.0,28.0,1006.1,1005.1,1.0,NaN,16.9,22.7,No
8,Row9,Albury,11.3,26.5,0.0,NaN,NaN,WNW,56.0,W,...,31.0,46.0,26.0,1004.5,1003.2,NaN,NaN,19.7,25.7,No
9,Row10,Albury,12.9,35.8,0.0,NaN,NaN,WNW,41.0,ENE,...,26.0,41.0,9.0,1012.6,1009.2,NaN,NaN,22.4,34.4,No


In [ ]:
df.tail(3)

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
42674,Row43635,Uluru,2.6,22.5,0.0,NaN,NaN,S,19.0,S,...,7.0,59.0,24.0,1025.0,1021.4,NaN,NaN,8.8,22.1,No
42675,Row43636,Uluru,7.4,20.6,0.0,NaN,NaN,E,35.0,ESE,...,17.0,63.0,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,No
42676,Row43637,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,7.0,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No


In [ ]:
df.isnull()

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
2,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
4,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42672,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
42673,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
42674,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
42675,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False


In [ ]:
df.isnull().sum()

,0
row ID,0
Location,0
MinTemp,194
MaxTemp,92
Rainfall,427
Evaporation,18312
Sunshine,20499
WindGustDir,2809
WindGustSpeed,2790
WindDir9am,3007


In [ ]:
df.isnull().sum().sum()

np.int64(95340)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  object 
 1   Location       42677 non-null  object 
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    39868 non-null  object 
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     39670 non-null  object 
 10  WindDir3pm     41547 non-null  object 
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float64
 14  Humidity3pm    41573 non-null  float64
 15  Pressure9am    38411 non-null  float64
 16  Pressure3pm    38432 non-null  float64
 17  Cloud9am       26592 non-null  float64
 18  Cloud3

In [ ]:
df.shape

(42677, 22)

In [ ]:
df.columns

Index(['row ID', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday'],
      dtype='object')

In [ ]:
df['RainToday']

,RainToday
0,No
1,No
2,No
3,No
4,Yes
5,No
6,No
7,No


In [ ]:
df[['Temp9am','RainToday','Temp3pm']].head()

,Temp9am,RainToday,Temp3pm
0,21.0,No,23.2
1,18.1,No,26.5
2,18.1,No,24.6
3,18.3,No,30.2
4,17.4,Yes,15.8


In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#df.drop_duplicates(inplace=True)

In [ ]:
df.dtypes

,0
row ID,object
Location,object
MinTemp,float64
MaxTemp,float64
Rainfall,float64
Evaporation,float64
Sunshine,float64
WindGustDir,object
WindGustSpeed,float64
WindDir9am,object


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['RainToday']=le.fit_transform(df['RainToday'])
df['Location']=le.fit_transform(df['Location'])
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  object 
 1   Location       42677 non-null  int64  
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    39868 non-null  object 
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     39670 non-null  object 
 10  WindDir3pm     41547 non-null  object 
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float64
 14  Humidity3pm    41573 non-null  float64
 15  Pressure9am    38411 non-null  float64
 16  Pressure3pm    38432 non-null  float64
 17  Cloud9am       26592 non-null  float64
 18  Cloud3

In [ ]:
df.head(10)

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,Row0,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
1,Row1,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
2,Row2,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,24.0,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No
3,Row3,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,28.0,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No
4,Row4,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,28.0,76.0,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes
5,Row6,Albury,11.5,29.3,0.0,NaN,NaN,S,24.0,SE,...,9.0,56.0,28.0,1019.3,1014.8,NaN,NaN,19.1,27.3,No
6,Row7,Albury,16.2,33.9,0.0,NaN,NaN,WSW,35.0,SE,...,13.0,45.0,19.0,1010.9,1007.6,NaN,1.0,23.2,33.0,No
7,Row8,Albury,12.0,24.4,0.8,NaN,NaN,W,39.0,WNW,...,17.0,48.0,28.0,1006.1,1005.1,1.0,NaN,16.9,22.7,No
8,Row9,Albury,11.3,26.5,0.0,NaN,NaN,WNW,56.0,W,...,31.0,46.0,26.0,1004.5,1003.2,NaN,NaN,19.7,25.7,No
9,Row10,Albury,12.9,35.8,0.0,NaN,NaN,WNW,41.0,ENE,...,26.0,41.0,9.0,1012.6,1009.2,NaN,NaN,22.4,34.4,No


In [ ]:
df.tail(2)

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
42675,Row43636,Uluru,7.4,20.6,0.0,NaN,NaN,E,35.0,ESE,...,17.0,63.0,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,No
42676,Row43637,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,7.0,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  object 
 1   Location       42677 non-null  object 
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    39868 non-null  object 
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     39670 non-null  object 
 10  WindDir3pm     41547 non-null  object 
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float64
 14  Humidity3pm    41573 non-null  float64
 15  Pressure9am    38411 non-null  float64
 16  Pressure3pm    38432 non-null  float64
 17  Cloud9am       26592 non-null  float64
 18  Cloud3

In [ ]:
df.shape

(42677, 22)

In [ ]:
df.shape

(42677, 22)

In [ ]:
df.columns

Index(['row ID', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday'],
      dtype='object')

In [ ]:
df.isnull()

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
2,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
4,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42672,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
42673,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
42674,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False
42675,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False


In [ ]:
df.isnull().sum()

,0
row ID,0
Location,0
MinTemp,194
MaxTemp,92
Rainfall,427
Evaporation,18312
Sunshine,20499
WindGustDir,2809
WindGustSpeed,2790
WindDir9am,3007


In [ ]:
df.isnull().sum().sum()

np.int64(95340)

In [ ]:
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
count,42483.000000,42585.000000,42250.000000,24365.000000,22178.000000,39887.000000,42264.000000,41882.000000,42136.000000,41573.000000,38411.000000,38432.000000,26592.000000,25585.000000,42387.000000,41855.000000
mean,12.210032,23.246068,2.342862,5.489715,7.647831,40.001379,13.995315,18.607516,68.791176,51.597672,1017.581591,1015.192792,4.412041,4.466054,17.028266,21.700982
std,6.432122,7.123596,8.412106,4.248850,3.778019,13.605915,8.872445,8.806916,18.996115,20.844525,7.094070,7.016408,2.887927,2.729640,6.501771,6.951426
min,-8.200000,-4.800000,0.000000,0.000000,0.000000,7.000000,0.000000,0.000000,1.000000,1.000000,982.200000,977.100000,0.000000,0.000000,-7.200000,-5.400000
25%,7.600000,18.000000,0.000000,2.600000,4.900000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000
50%,12.000000,22.600000,0.000000,4.800000,8.500000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.800000,21.100000
75%,16.900000,28.300000,0.600000,7.400000,10.700000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.500000
max,31.800000,47.000000,278.400000,145.000000,14.300000,122.000000,74.000000,83.000000,100.000000,100.000000,1040.400000,1038.900000,8.000000,8.000000,39.400000,45.400000


In [ ]:
df['Location']

,Location
0,Albury
1,Albury
2,Albury
3,Albury
4,Albury
...,...
42672,Uluru
42673,Uluru
42674,Uluru
42675,Uluru


In [ ]:
df[['MaxTemp','Location']]

,MaxTemp,Location
0,25.7,Albury
1,28.0,Albury
2,25.0,Albury
3,31.9,Albury
4,18.6,Albury
...,...,...
42672,19.1,Uluru
42673,21.4,Uluru
42674,22.5,Uluru
42675,20.6,Uluru


In [ ]:
df['MaxTemp']

,MaxTemp
0,25.7
1,28.0
2,25.0
3,31.9
4,18.6
...,...
42672,19.1
42673,21.4
42674,22.5
42675,20.6


In [ ]:
df['RainToday'].value_counts()

,count
RainToday,
No,32851
Yes,9399


In [ ]:
df['RainToday'].unique()

array(['No', 'Yes', nan], dtype=object)

In [ ]:
df['RainToday'].nunique()

2

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["row ID"]=le.fit_transform(df["row ID"])
df["Location"]=le.fit_transform(df["Location"])
df["WindGustDir"]=le.fit_transform(df["WindGustDir"])
df["WindDir9am"]=le.fit_transform(df["WindDir9am"])
df["WindDir3pm"]=le.fit_transform(df["WindDir3pm"])
df["RainToday"]=le.fit_transform(df["RainToday"])
df


,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,0,2,12.9,25.7,0.0,NaN,NaN,15,46.0,13,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,0
1,1,2,9.2,28.0,0.0,NaN,NaN,4,24.0,9,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,0
2,10859,2,14.3,25.0,0.0,NaN,NaN,13,50.0,12,...,24.0,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,0
3,21632,2,9.7,31.9,0.0,NaN,NaN,6,80.0,9,...,28.0,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,0
4,32544,2,15.9,18.6,15.6,NaN,NaN,13,61.0,6,...,28.0,76.0,93.0,994.3,993.0,8.0,8.0,17.4,15.8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42672,36506,41,2.4,19.1,0.0,NaN,NaN,0,33.0,9,...,17.0,59.0,24.0,1030.0,1026.2,NaN,NaN,8.0,18.8,0
42673,36507,41,2.3,21.4,0.0,NaN,NaN,9,22.0,9,...,7.0,60.0,28.0,1026.9,1022.8,NaN,NaN,8.9,20.3,0
42674,36508,41,2.6,22.5,0.0,NaN,NaN,8,19.0,8,...,7.0,59.0,24.0,1025.0,1021.4,NaN,NaN,8.8,22.1,0
42675,36509,41,7.4,20.6,0.0,NaN,NaN,0,35.0,2,...,17.0,63.0,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,0


In [ ]:
df["MaxTemp"]=le.fit_transform(df["MaxTemp"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  int64  
 1   Location       42677 non-null  int64  
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42677 non-null  int64  
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    42677 non-null  int64  
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     42677 non-null  int64  
 10  WindDir3pm     42677 non-null  int64  
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float64
 14  Humidity3pm    41573 non-null  float64
 15  Pressure9am    38411 non-null  float64
 16  Pressure3pm    38432 non-null  float64
 17  Cloud9am       26592 non-null  float64
 18  Cloud3

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  int64  
 1   Location       42677 non-null  int64  
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42677 non-null  int64  
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    42677 non-null  int64  
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     42677 non-null  int64  
 10  WindDir3pm     42677 non-null  int64  
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float64
 14  Humidity3pm    41573 non-null  float64
 15  Pressure9am    38411 non-null  float64
 16  Pressure3pm    38432 non-null  float64
 17  Cloud9am       26592 non-null  float64
 18  Cloud3

In [ ]:
df.isnull().sum()

,0
row ID,0
Location,0
MinTemp,194
MaxTemp,0
Rainfall,427
Evaporation,18312
Sunshine,20499
WindGustDir,0
WindGustSpeed,2790
WindDir9am,0


In [ ]:
df['Cloud9am']=df['Cloud9am'].fillna(df['Cloud9am'].median())
df['Cloud3pm']=df['Cloud3pm'].fillna(df['Cloud3pm'].median())
df['Temp3pm']=df['Temp3pm'].fillna(df['Temp3pm'].median())
df['Temp9am']=df['Temp9am'].fillna(df['Temp9am'].median())
#df['RainTomorrow']=df['RainTomorrow'].fillna(df['RainTomorrow'].mode()[0])
df['Temp9am']=df['Temp9am'].fillna(df['Temp9am'].median())
df.isnull().sum()
#df.dropna(inplace=True)

,0
row ID,0
Location,0
MinTemp,194
MaxTemp,0
Rainfall,427
Evaporation,18312
Sunshine,20499
WindGustDir,0
WindGustSpeed,2790
WindDir9am,0


In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

,0
row ID,0
Location,0
MinTemp,0
MaxTemp,0
Rainfall,0
Evaporation,0
Sunshine,0
WindGustDir,0
WindGustSpeed,0
WindDir9am,0


In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(19473, 22)

In [ ]:
#df.drop_duplicates(inplace=True)

In [ ]:
x=df.drop(["RainToday"],axis=1)


y=df["RainToday"]
x
#y

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
1756,8497,10,18.4,302,0.0,14.8,13.0,8,37.0,10,...,19.0,19.0,30.0,8.0,1012.9,1012.1,1.0,1.0,20.3,27.0
1757,8508,10,19.4,389,0.0,10.8,10.6,5,46.0,5,...,30.0,15.0,42.0,22.0,1012.3,1009.2,1.0,6.0,28.7,34.9
1758,8519,10,21.9,397,0.0,11.4,12.2,14,31.0,14,...,6.0,6.0,37.0,22.0,1012.7,1009.1,1.0,5.0,29.1,35.6
1759,8531,10,24.2,423,0.0,11.2,8.4,14,35.0,7,...,17.0,13.0,19.0,15.0,1010.7,1007.4,1.0,6.0,33.6,37.6
1760,8542,10,19.7,368,0.0,11.0,12.7,4,41.0,5,...,15.0,17.0,61.0,14.0,1007.9,1005.8,1.0,5.0,24.0,33.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41697,35436,13,17.2,304,0.0,7.2,10.1,2,44.0,2,...,15.0,20.0,41.0,21.0,1017.6,1014.1,1.0,2.0,20.9,28.5
41698,35437,13,18.3,311,0.0,8.4,10.5,2,41.0,2,...,19.0,13.0,43.0,24.0,1016.7,1013.1,3.0,2.0,21.9,29.4
41699,35438,13,16.9,316,0.0,5.4,10.9,0,33.0,2,...,11.0,17.0,41.0,43.0,1016.6,1012.9,1.0,0.0,21.8,28.7
41700,35439,13,20.2,334,0.0,4.8,9.9,0,31.0,9,...,11.0,11.0,51.0,35.0,1014.5,1011.4,1.0,3.0,23.9,31.2


In [ ]:
y

,RainToday
1756,0
1757,0
1758,0
1759,0
1760,0
...,...
41697,0
41698,0
41699,0
41700,0


In [ ]:
from sklearn.preprocessing import MinMaxScaler  #StandardScaler
sc=MinMaxScaler()
c=sc.fit_transform(x)
print(c)
#

[[0.19901104 0.20833333 0.63978495 ... 0.125      0.52369077 0.558753  ]
 [0.19926882 0.20833333 0.66666667 ... 0.75       0.73316708 0.74820144]
 [0.19952661 0.20833333 0.73387097 ... 0.625      0.74314214 0.76498801]
 ...
 [0.8303766  0.27083333 0.59946237 ... 0.         0.56109726 0.59952038]
 [0.83040004 0.27083333 0.68817204 ... 0.375      0.61346633 0.65947242]
 [0.83044691 0.27083333 0.66935484 ... 0.125      0.63591022 0.61151079]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
from sklearn.linear_model import LogisticRegression  #LinearRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_train)
y_pred

(15578, 21)
(3895, 21)
(15578,)
(3895,)


array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report  #r2_score,mean_squared_error,mean_absolute_error
print(accuracy_score(y_train,y_pred))
print(confusion_matrix(y_train,y_pred))
print(classification_report(y_train,y_pred))
#

0.8913992297817716
[[3001   63]
 [ 360  471]]
              precision    recall  f1-score   support

           0       0.89      0.98      0.93      3064
           1       0.88      0.57      0.69       831

    accuracy                           0.89      3895
   macro avg       0.89      0.77      0.81      3895
weighted avg       0.89      0.89      0.88      3895



In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report  #r2_score
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8649550706033377
[[2947  117]
 [ 409  422]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      3064
           1       0.78      0.51      0.62       831

    accuracy                           0.86      3895
   macro avg       0.83      0.73      0.77      3895
weighted avg       0.86      0.86      0.85      3895



In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
#

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[3064    0]
 [   0  831]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3064
           1       1.00      1.00      1.00       831

    accuracy                           1.00      3895
   macro avg       1.00      1.00      1.00      3895
weighted avg       1.00      1.00      1.00      3895



In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_test,y_test)
y_pred=dt.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[3064    0]
 [   0  831]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3064
           1       1.00      1.00      1.00       831

    accuracy                           1.00      3895
   macro avg       1.00      1.00      1.00      3895
weighted avg       1.00      1.00      1.00      3895



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
#

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[3064    0]
 [   0  831]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3064
           1       1.00      1.00      1.00       831

    accuracy                           1.00      3895
   macro avg       1.00      1.00      1.00      3895
weighted avg       1.00      1.00      1.00      3895



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_test,y_test)
y_pred=rf.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[3064    0]
 [   0  831]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3064
           1       1.00      1.00      1.00       831

    accuracy                           1.00      3895
   macro avg       1.00      1.00      1.00      3895
weighted avg       1.00      1.00      1.00      3895



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
#

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8284980744544288
[[2833  231]
 [ 437  394]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.89      3064
           1       0.63      0.47      0.54       831

    accuracy                           0.83      3895
   macro avg       0.75      0.70      0.72      3895
weighted avg       0.82      0.83      0.82      3895



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_test,y_test)
y_pred=knn.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8785622593068035
[[2934  130]
 [ 343  488]]
              precision    recall  f1-score   support

           0       0.90      0.96      0.93      3064
           1       0.79      0.59      0.67       831

    accuracy                           0.88      3895
   macro avg       0.84      0.77      0.80      3895
weighted avg       0.87      0.88      0.87      3895



In [ ]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
#

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8921694480102695
[[3024   40]
 [ 380  451]]
              precision    recall  f1-score   support

           0       0.89      0.99      0.94      3064
           1       0.92      0.54      0.68       831

    accuracy                           0.89      3895
   macro avg       0.90      0.76      0.81      3895
weighted avg       0.89      0.89      0.88      3895



In [ ]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_test,y_test)
y_pred=svc.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8852374839537869
[[3009   55]
 [ 392  439]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93      3064
           1       0.89      0.53      0.66       831

    accuracy                           0.89      3895
   macro avg       0.89      0.76      0.80      3895
weighted avg       0.89      0.89      0.87      3895



In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
#

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9386392811296534
[[2826  238]
 [   1  830]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96      3064
           1       0.78      1.00      0.87       831

    accuracy                           0.94      3895
   macro avg       0.89      0.96      0.92      3895
weighted avg       0.95      0.94      0.94      3895



In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_test,y_test)
y_pred=nb.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9391527599486521
[[2828  236]
 [   1  830]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96      3064
           1       0.78      1.00      0.88       831

    accuracy                           0.94      3895
   macro avg       0.89      0.96      0.92      3895
weighted avg       0.95      0.94      0.94      3895

